artifact version overlap check 2

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -45,7 +45,8 @@ jobs:
         ARTIFACT_LIST=( $(gcloud artifacts versions list --repository=sampleappmvn --package=$PACKAGE:$ARTIFACT_ID --project=$PROJECT_ID --location=$REGION --format="value(VERSION)") )
         if [[ " ${ARTIFACT_LIST[*]} " =~ " ${APP_VERSION} " ]]
         then
-          echo "Version already exists"
+          echo "[ ERROR ] Version already exists in Artifact Registry!!!"
+          exit 1
         fi
         echo "ART_VERSION=$ARTIFACT_LIST" >> $GITHUB_OUTPUT
 
